### PR TITLE
Add ability to upload title screens

### PR DESCRIPTION
**Pull request by StrAbZ**
The purpose of this PR is to allow users to upload game titlescreens in a differents category, other than screenshots for example.

### CODE REVIEW

**Comment by Zer0xFF** [comment]
Thanks for the changes, on quick inspection everything looks good to me. I'd run it on my dev server to test them out before I merge them, in the mean while, I'm checking with the mods to see if we should perhaps limit the upload to 1 title screen per game.

**Comment by StrAbZ** [comment]
Yes I thought about it. I don’t think we need more than one title screen per game.

**Comment by Zer0xFF** [comment]
OK, so we won't be limiting it, the mods did suggest potential alternative title screen, which reminded of atleast 1 example, FFXV title screen changes after you complete the game, and each DLCs have their own title screens.

**Comment by Zer0xFF** [comment]
Thanks for the PR, changes have been merged and are live now :)

**Pull request merged**
